### ISSUE TITLE
Typescript Type Definitions

### ISSUE THREAD

**Issue by rcollette** [okta/okta-oidc-middleware#57]
### Describe the feature request?

I am requesting Typescript type definition be added to make the development experience more pleasant.

The okta-jwt-verifier library implements type definitions but this one does not.

### New or Affected Resource(s)

The new resource would be a type definition file (.d.ts)

### Provide a documentation link

For reference see:
https://github.com/okta/okta-jwt-verifier-js/blob/master/lib.d.ts

**Comment by rcollette** [comment]
Having the Constructor and it's configuration options typed would be helpful.

**Comment by denysoblohin-okta** [comment]
Internal ref: OKTA-570203

**Comment by denysoblohin-okta** [comment]
@rcollette Please use version 5.1.0
