### ISSUE TITLE
Support node 18 (current LTS)

### ISSUE THREAD

**Issue by mbyrne00** [okta/okta-oidc-middleware#59]
### Describe the bug?

The `engines` for this lib does not allow for the current (at time of raising) LTS version of node. See https://github.com/okta/okta-oidc-middleware/blob/357c1f23701703f44a73ec5d19476e29a583f4cf/package.json#L37

### What is expected to happen?

Would hope lib should always support current LTS. Update engines with node `18` support. Verify all works as expected.

### What is the actual behavior?

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/5687982/216855779-31d178fe-6ded-41d3-89d1-801ea0bf749c.png">

### Reproduction Steps?

Install node 18, then `npm i`

### SDK Versions

`@okta/oidc-middleware`  `5.0.0`

### Execution Environment

Any environment

**Comment by denysoblohin-okta** [comment]
Thanks for opening this issue.
Internal ref: OKTA-574451

**Comment by jaredperreault-okta** [comment]
@mbyrne00 Node 18 support was just added with the `5.0.1` release

**Comment by mbyrne00** [comment]
Great! Thanks for the quick turnaround.
