### ISSUE TITLE
Any plans to switch csrf package from csurf?

### ISSUE THREAD

**Issue by sfc-gh-mlipski** [okta/okta-oidc-middleware#63]
### Describe the feature request?

Hi, according to their page https://www.npmjs.com/package/csurf has beed deprecated and will not be maintained.

The current version has security issue: https://security.snyk.io/vuln/SNYK-JS-CSURF-3021144

Do you have any plans in near future to switch to different package?

### New or Affected Resource(s)

csurf dependency

**Comment by denysoblohin-okta** [comment]
According to [the package page on Snyk](https://security.snyk.io/package/npm/csurf), there is no registered vulnerabilities in the package.
Page https://security.snyk.io/vuln/SNYK-JS-CSURF-3021144 says "This was deemed not a vulnerability."

**Comment by shuowu-okta** [comment]
Internal Ref: OKTA-579870

**Comment by sfc-gh-mlipski** [comment]
> According to [the package page on Snyk](https://security.snyk.io/package/npm/csurf), there is no registered vulnerabilities in the package. Page https://security.snyk.io/vuln/SNYK-JS-CSURF-3021144 says "This was deemed not a vulnerability."

oh, sorry I didn't notice the explanation in snyk. Looks like false alarm.
