### ISSUE TITLE
CSURF is deprecated

### ISSUE THREAD

**Issue by satyavh** [okta/okta-oidc-middleware#76]
### Describe the bug

When installing this package, the following deprecation warning shows

`npm WARN deprecated csurf@1.11.0: Please use another csrf package`

Which is correct, given this page
https://www.npmjs.com/package/csurf

### Reproduction Steps?

install this package

### SDK Versions

N/A

### Additional Information

I expect Okta - all about security - to be more on top of dependencies. Hope gets fixed soon.

**Comment by jaredperreault-okta** [comment]
This was been updated in `.5.4.0`
https://github.com/okta/okta-oidc-middleware/pull/78
